"""add_avatar_url

Revision ID: 1283c3c7fc54
Revises: d4e5f6a7b8c9
Create Date: 2026-03-29 01:35:11.017363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1283c3c7fc54'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractor_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contractor_reviews_contractor_id'))
        batch_op.create_index(batch_op.f('ix_contractor_reviews_id'), ['id'], unique=False)

    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(), nullable=True))

    with op.batch_alter_table('landlords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(), nullable=True))

    with op.batch_alter_table('maintenance_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_notes_request_id'))
        batch_op.create_index(batch_op.f('ix_maintenance_notes_id'), ['id'], unique=False)

    with op.batch_alter_table('rent_payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_rent_payments_lease_due'), type_='unique')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('rent_payments', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_rent_payments_lease_due'), ['lease_id', 'due_date'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('maintenance_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_notes_id'))
        batch_op.create_index(batch_op.f('ix_maintenance_notes_request_id'), ['maintenance_request_id'], unique=False)

    with op.batch_alter_table('landlords', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('contractor_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contractor_reviews_id'))
        batch_op.create_index(batch_op.f('ix_contractor_reviews_contractor_id'), ['contractor_id'], unique=False)

    # ### end Alembic commands ###
