"""add_esignature_columns_to_uploaded_files

Revision ID: 607d1ffd71fd
Revises: h3i4j5k6l7m8
Create Date: 2026-04-10 05:46:30.916322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '607d1ffd71fd'
down_revision: Union[str, Sequence[str], None] = 'h3i4j5k6l7m8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_valuation_requests')
    op.drop_table('public_blog_posts')
    with op.batch_alter_table('tenant_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_messages_id'))

    op.drop_table('tenant_messages')
    with op.batch_alter_table('public_saved_searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_saved_searches_id'))

    op.drop_table('public_saved_searches')
    op.drop_table('public_reviews')
    with op.batch_alter_table('meter_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meter_readings_id'))

    op.drop_table('meter_readings')
    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_claims_org'))
        batch_op.drop_index(batch_op.f('ix_insurance_claims_property'))
        batch_op.create_index(batch_op.f('ix_insurance_claims_id'), ['id'], unique=False)

    with op.batch_alter_table('telegram_inventory_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_inventory_sessions_id'), ['id'], unique=False)

    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('signed_by_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('signature_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_column('signature_data')
        batch_op.drop_column('signed_by_name')
        batch_op.drop_column('signed_at')

    with op.batch_alter_table('telegram_inventory_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_inventory_sessions_id'))

    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_claims_id'))
        batch_op.create_index(batch_op.f('ix_insurance_claims_property'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_claims_org'), ['organisation_id'], unique=False)

    op.create_table('meter_readings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meter_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reading', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reading_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submitted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('meter_readings_organisation_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('meter_readings_tenant_id_fkey')),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('meter_readings_unit_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('meter_readings_pkey'))
    )
    with op.batch_alter_table('meter_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meter_readings_id'), ['id'], unique=False)

    op.create_table('public_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reviewer_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reviewer_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('property_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('public_reviews_organisation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('public_reviews_pkey'))
    )
    op.create_table('public_saved_searches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filters_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_notified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('public_saved_searches_organisation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('public_saved_searches_pkey')),
    sa.UniqueConstraint('token', name=op.f('public_saved_searches_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('public_saved_searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_saved_searches_id'), ['id'], unique=False)

    op.create_table('tenant_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sender_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('tenant_messages_organisation_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('tenant_messages_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tenant_messages_pkey'))
    )
    with op.batch_alter_table('tenant_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_messages_id'), ['id'], unique=False)

    op.create_table('public_blog_posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('excerpt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cover_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('public_blog_posts_organisation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('public_blog_posts_pkey'))
    )
    op.create_table('public_valuation_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('property_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bedrooms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('public_valuation_requests_organisation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('public_valuation_requests_pkey'))
    )
    # ### end Alembic commands ###
