"""add_epc_rating_to_properties

Revision ID: 697142de6bff
Revises: 40e649c57b4c
Create Date: 2026-04-01 06:05:55.779500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697142de6bff'
down_revision: Union[str, Sequence[str], None] = '40e649c57b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('epc_rating', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('epc_rating')

    # ### end Alembic commands ###
