"""add_organisation_billing_fields

Revision ID: 6f2c2cb176d1
Revises: 33511e2a0c65
Create Date: 2026-03-26 06:55:23.095761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2c2cb176d1'
down_revision: Union[str, Sequence[str], None] = '33511e2a0c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_unique_constraint(None, ['stripe_customer_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('trial_ends_at')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
