"""add_property_epc_roadmaps

Revision ID: 74aa7f788227
Revises: 697142de6bff
Create Date: 2026-04-01 06:42:27.751512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74aa7f788227'
down_revision: Union[str, Sequence[str], None] = '697142de6bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_epc_roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('epc_rating', sa.String(length=1), nullable=False),
    sa.Column('target_date', sa.String(), nullable=True),
    sa.Column('improvements_json', sa.Text(), nullable=False),
    sa.Column('property_name', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_epc_roadmaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_epc_roadmaps_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_epc_roadmaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_epc_roadmaps_id'))

    op.drop_table('property_epc_roadmaps')
    # ### end Alembic commands ###
