"""add_contractor_last_login

Revision ID: 8aa4c1a0e17f
Revises: c2d8205b3941
Create Date: 2026-03-29 15:02:30.869955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa4c1a0e17f'
down_revision: Union[str, Sequence[str], None] = 'c2d8205b3941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
