"""add_notification_prefs_to_tenant_landlord_contractor

Revision ID: a4d32ac059ad
Revises: 4fa9cc04985a
Create Date: 2026-04-10 06:30:53.891200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d32ac059ad'
down_revision: Union[str, Sequence[str], None] = '4fa9cc04985a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notify_email', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_whatsapp', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_telegram', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('telegram_link_code', sa.String(), nullable=True))

    with op.batch_alter_table('landlords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notify_email', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_whatsapp', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_telegram', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('telegram_link_code', sa.String(), nullable=True))

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_email', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_whatsapp', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_telegram', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('telegram_link_code', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('telegram_link_code')
        batch_op.drop_column('telegram_chat_id')
        batch_op.drop_column('notify_telegram')
        batch_op.drop_column('notify_whatsapp')
        batch_op.drop_column('notify_email')

    with op.batch_alter_table('landlords', schema=None) as batch_op:
        batch_op.drop_column('telegram_link_code')
        batch_op.drop_column('telegram_chat_id')
        batch_op.drop_column('notify_telegram')
        batch_op.drop_column('notify_whatsapp')
        batch_op.drop_column('notify_email')
        batch_op.drop_column('whatsapp_number')

    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.drop_column('telegram_link_code')
        batch_op.drop_column('telegram_chat_id')
        batch_op.drop_column('notify_telegram')
        batch_op.drop_column('notify_whatsapp')
        batch_op.drop_column('notify_email')
        batch_op.drop_column('whatsapp_number')

    # ### end Alembic commands ###
