"""baseline: all current tables

Revision ID: b8184996d912
Revises: 
Create Date: 2026-03-25 17:12:53.891728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8184996d912'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portal_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portal_messages_id'), ['id'], unique=False)

    op.create_table('tenant_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_notifications_id'), ['id'], unique=False)

    op.create_table('ppm_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('next_due', sa.Date(), nullable=False),
    sa.Column('last_triggered', sa.Date(), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ppm_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ppm_schedules_id'), ['id'], unique=False)

    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'contractors', ['contractor_id'], ['id'])

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_number', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_number')

    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ppm_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ppm_schedules_id'))

    op.drop_table('ppm_schedules')
    with op.batch_alter_table('tenant_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_notifications_id'))

    op.drop_table('tenant_notifications')
    with op.batch_alter_table('portal_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portal_messages_id'))

    op.drop_table('portal_messages')
    # ### end Alembic commands ###
