"""add_landlord_detail_fields

Revision ID: c2d8205b3941
Revises: 91aaf8712c96
Create Date: 2026-03-29 09:56:02.203911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d8205b3941'
down_revision: Union[str, Sequence[str], None] = '91aaf8712c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_line1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address_line2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('postcode', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('company_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('vat_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sort_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlords', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('account_number')
        batch_op.drop_column('sort_code')
        batch_op.drop_column('account_name')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('vat_number')
        batch_op.drop_column('company_number')
        batch_op.drop_column('company_name')
        batch_op.drop_column('postcode')
        batch_op.drop_column('city')
        batch_op.drop_column('address_line2')
        batch_op.drop_column('address_line1')

    # ### end Alembic commands ###
