"""rtr_tenant_fields_surveys

Revision ID: d0219d233a3b
Revises: 6f2c2cb176d1
Create Date: 2026-03-27 10:37:53.073560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0219d233a3b'
down_revision: Union[str, Sequence[str], None] = '6f2c2cb176d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['maintenance_requests.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_surveys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_surveys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_surveys_token'), ['token'], unique=True)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rtr_document_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rtr_check_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rtr_expiry_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('rtr_expiry_date')
        batch_op.drop_column('rtr_check_date')
        batch_op.drop_column('rtr_document_type')

    with op.batch_alter_table('maintenance_surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_surveys_token'))
        batch_op.drop_index(batch_op.f('ix_maintenance_surveys_id'))

    op.drop_table('maintenance_surveys')
    # ### end Alembic commands ###
