import { Link } from 'react-router-dom'

export default function Terms() {
  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white border-b border-gray-200 px-8 py-4 flex items-center justify-between">
        <Link to="/" className="text-xl font-bold text-indigo-600">Prop<span className="text-gray-900">AI</span>rty</Link>
        <Link to="/login" className="text-sm text-gray-500 hover:text-gray-900">Sign in</Link>
      </header>
      <div className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-8">Last updated: March 2026</p>

        <div className="space-y-8 text-sm text-gray-700 leading-relaxed">

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">1. Agreement</h2>
            <p>By creating an account on PropAIrty ("the Service"), operated by Genaixa Ltd ("we", "us", "our"), you agree to these Terms of Service. If you are signing up on behalf of a company or letting agency, you confirm you have authority to bind that organisation to these terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">2. The Service</h2>
            <p>PropAIrty provides property management software to letting agents. The Service includes tools for managing properties, tenants, leases, maintenance, compliance, and communications. We provide portals for landlords, tenants and contractors as part of the Service.</p>
            <p className="mt-2">PropAIrty is a software platform only. We are not a letting agent, property manager, legal adviser, or financial adviser. Nothing in the Service constitutes legal or financial advice.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">3. Subscriptions and payment</h2>
            <p>Access to the Service requires an active paid subscription. Subscriptions are billed monthly in advance. Prices are shown on our pricing page and may change with 30 days' notice.</p>
            <p className="mt-2">New accounts receive a 14-day free trial. No credit card is required to start a trial. After the trial, a valid payment method is required to continue using the Service.</p>
            <p className="mt-2">Payments are processed by Stripe. We do not store your card details. Refunds are at our discretion and assessed on a case-by-case basis.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">4. Your responsibilities</h2>
            <p>You are responsible for:</p>
            <ul className="list-disc list-inside space-y-1 mt-1">
              <li>The accuracy of data you enter into the Service</li>
              <li>Obtaining consent from tenants and contractors to store their personal data</li>
              <li>Complying with all applicable laws including the Housing Act, GDPR, and tenancy deposit regulations</li>
              <li>Keeping your login credentials secure</li>
              <li>Any automated documents (Section 21, Section 8, etc.) generated by the Service — you must review these before serving them</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">5. Automated documents</h2>
            <p>The Service can generate legal notices (Section 21, Section 8, rent increase letters). These are provided as templates only. You must review all documents for accuracy before serving them to tenants. Genaixa Ltd accepts no liability for documents served without review or for errors arising from incorrect data entered by users.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">6. AI features</h2>
            <p>PropAIrty uses AI (Anthropic Claude) for features including an AI assistant and risk scoring. AI outputs may contain errors and should not be relied upon as legal, financial or professional advice. You are responsible for verifying AI-generated content before acting on it.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">7. Data and privacy</h2>
            <p>Your use of personal data within the Service is governed by our <Link to="/privacy" className="text-indigo-600 hover:underline">Privacy Policy</Link>. As a letting agent using PropAIrty, you are a Data Controller for the personal data of your tenants, landlords and contractors. Genaixa Ltd acts as a Data Processor on your behalf.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">8. Uptime and availability</h2>
            <p>We aim for high availability but do not guarantee uninterrupted access to the Service. Planned maintenance will be communicated in advance where possible. We are not liable for losses arising from unavailability of the Service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">9. Limitation of liability</h2>
            <p>To the maximum extent permitted by law, Genaixa Ltd's total liability to you for any claim arising from use of the Service shall not exceed the total fees paid by you in the 12 months preceding the claim. We are not liable for indirect, incidental, or consequential losses.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">10. Termination</h2>
            <p>You may cancel your subscription at any time via the billing settings. Access continues until the end of your paid period. We may suspend or terminate accounts that breach these terms, with or without notice depending on severity.</p>
            <p className="mt-2">On termination, you may request an export of your data within 30 days. After 30 days, data may be deleted in accordance with our Privacy Policy.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">11. Governing law</h2>
            <p>These terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">12. Contact</h2>
            <p>Genaixa Ltd<br />
            Email: <a href="mailto:hello@propairty.co.uk" className="text-indigo-600 hover:underline">hello@propairty.co.uk</a></p>
          </section>

        </div>
      </div>
      <footer className="border-t border-gray-200 mt-12 py-6 text-center text-xs text-gray-400">
        <Link to="/terms" className="hover:underline mr-4">Terms of Service</Link>
        <Link to="/privacy" className="hover:underline">Privacy Policy</Link>
        <span className="mx-4">·</span>
        © 2026 Genaixa Ltd
      </footer>
    </div>
  )
}
